### ISSUE TITLE
The ability to support multiple AWS query types in one connector

### ISSUE THREAD

**Issue by farchide** [prancer-io/cloud-validation-framework#17]
## Background

in prancer validation framework, to connect to an AWS backend, we create the AWS connector:

```
{
    "organization": "company1",
    "type": "aws",
    "fileType": "structure",
    "organization-unit": [
        {
            "name": "abc",
            "accounts": [
                {
                    "account-name": "acc-name",
                    "account-description": "AWS cloud details",
                    "account-id": "<id>",
                    "account-user": "<user>",
                    "users": [
                        {
                            "name": "<user>",
                            "access-key": "<key>",
                            "secret-access": "",
                            "region":"us-west-2",
                            "client": "EC2"
                        }
                    ]
                }
            ]
        }
    ]
}
```

in the client section we define the type of the query we want to pass to the AWS backend.

## Problem
The issue is if we want to use other form of AWS queries (i.e. RDS), we need to create a new connector.

## Solution
This setting should be available at the snapshot level rather than the connector level. By doing that, we will be able to reuse a single connector type for different queries.

**Comment by patidarpraveen244** [comment]
I have updated the code to now accept **client** and **region** from the snapshot file as well (with the same key name). If either fields are not available in snapshot file, the field provided in the Connector will be used.
