### ISSUE TITLE
prancer cyberark integration

### ISSUE THREAD

**Issue by farchide** [prancer-io/cloud-validation-framework#18]
Currently, prancer validation framework can connect to the Azure Keyvault and read the secrets from there. 
There are many companies using Cyber Ark (https://www.cyberark.com/) as the secret management tool.
Prancer validation framework should be able to connect to the Cyber Ark and read the secrets.
the configuration values should be placed in the config.ini file.

**Comment by ajeybk** [comment]
Cyberark provides two methods of integration for secret management:
1) REST calls to get the secrets with application Id and ObjectName as inputs. Any library or utility capable of making secure REST calls should be able to use the REST calls.
2) Install Cyberark SDK tools and invoke the binaries with application ID and objectName to retrieve the secrets. Support of native binaries is available for windows and Linux systems, Mac OS is unsupported.

The possible avenues for cyberark integration into prancer-basic are as:
1) Install cyberark sdk tools and the prancer-basic invokes these external binaries to retrieve secret data. Users have to install SDK tools for supported OS. Limits that some OSes (eg: MAC OS is not supported)
2) Have external utilities like curl, wget to make REST calls. The binaries should be in the path and should be user installed and its platform independent. curl is an installation of its own binaries on the platform. And it is available on all platforms. Curl also becomes an external dependencies. It's a n OS level installation not python dependency
3) Use python library (https://github.com/infamousjoeg/pyAIM) that provides both the above methods. Internally the library used urllib of the python standard library. Shall be platform independent.
4) https://github.com/infamousjoeg/pyaim/blob/master/pyaim/aimccp.py - This is the rest call using the standard urllib library and this will be platform independent and will work for mac OS too. Prancer-basic supports only REST cyberark integration. And shall not be dependent on any third party library. The code needs to be updated to the changes with respect to REST calls in future.

After the above listed points towards each method, using method (4) of the library or import/copy the code from the file in prancer-basic makes most viable method.
cyberark can be integrated in prancer-basic. The flow of getting secrets by connectors is as :
1) Check in secret configuration in the connector config file.
2) If not present, then try the common vault config and retrieve values from the vault.
3) If still not got the secret for the connector, try the environment variable for CLIENTKEY
4) If still not found, then prompt for it as a command line.

We can integrate the cyberark at point (2), check if the vault type is CYBERARK, read the values of appid and the objectName for retrieving the credentials.

This will be generic integration for all connectors

**Comment by crazycodr** [comment]
I approve. Keys for CyberArk identification should be readable from ENV, not just from config or STDIN

**Comment by farchide** [comment]
The ordering should be like this:
1. Check in secret configuration in the connector config file.
2. If still not got the secret for the connector, try the environment variable for CLIENTKEY
3. If not present, then try the common vault config and retrieve values from the vault.
4. If still not found, then prompt for it as a command line.

The reason is usually we should be able to overwrite the global var by setting a local var

**Comment by crazycodr** [comment]
Then, it should be any env vars first as they are the most common form of
live overriding...

**Comment by farchide** [comment]
based on the new functionality:
For azure vault configuration:
[VAULT]
type = azure
tenant_id = 'Tenant Id'
client_id = 'Service Principal Id'
keyvault = 'Keyvault where secrets are stored'

For cyberark vault configuration:
[VAULT]
type = cyberark
CA_OBJECT = 'object name'
CA_SAFE = True
CA_EXE = 'Path to the cyberark executable'
CA_APPID = 'APP ID used for storing the object name'

**Comment by farchide** [comment]
PR merged
