### ISSUE TITLE
Dev pipeline should test on various python versions

### ISSUE THREAD

**Issue by farchide** [prancer-io/cloud-validation-framework#185]
We should make sure our framework is running on multiple versions of python.
We should validate the framework for python versions:

- 3.6.8
- 3.8
- 3.9

for this pipeline:
https://github.com/prancer-io/cloud-validation-framework/blob/master/.github/workflows/test_development.yaml

**Comment by danielalejandrohc** [comment]
Hi Farshide. This was closed on this PR https://github.com/prancer-io/cloud-validation-framework/pull/184/files
