### ISSUE TITLE
1) create special crawler to crawl azure role definitions

### ISSUE THREAD

**Issue by ajeybk** [prancer-io/cloud-validation-framework#187]
1) create special crawler to crawl azure role definitions ( resource type : "Microsoft.Authorization/roleDefinitions")
These resources do not get listed during the crawling operation, so specific queries have to be made for the resource. 
Add the framewpork for extending to these type of resources.

**Comment by vatsalgit5118** [comment]
Now, prancer basic supports the crawler for `Microsoft.Authorization/roleDefinitions` resource type.
Released in 1.1.0
