### ISSUE TITLE
git connector private ssh attributes

### ISSUE THREAD

**Issue by farchide** [prancer-io/cloud-validation-framework#19]
if we are doing authentication to access a git repo, `gitProvider` and `sshHost` are not the same here:
```
{
    "fileType": "structure",
    "companyName": "Organization name",
    "gitProvider": "<url-to-repository>",
    "branchName": "<branch>",
    "sshKeyfile": "<path-to-private-ssh-key-file>",
    "sshUser": "<username-of-repo>",
    "sshHost": "<hostname-of-repo>",
    "private": true
}
```
for example in Azure DevOps repo example:
`"gitProvider": "orgname@vs-ssh.visualstudio.com:v3/orgname/whitekite/whitekite"`
and
`"sshHost": "https://orgna,e.visualstudio.com/whitekite/_git/whitekite"`

we need to update this page:
http://docs.prancer.io/connectors/git/

**Comment by crazycodr** [comment]
How is sshHost supposed to have an https endpoint? I'm a little confused...

**Comment by ajeybk** [comment]
Yes it should not have https, it could be an ipaddress or just the domain name
eg: githug.com, bitbucket.org, vs-ssh.visualstudio.com

The ipadress or the domain name will be added to a ssh config file.

Host vs-ssh.visualstudio.com
     HostName vs-ssh.visualstudio.com
     User git
     Port 22
     IdentityFile /home/user/sshkeydir/id_rsa_vss

Host 192.168.1.2
     HostName 192.168.1.2
     User git
     Port 22
     IdentityFile /home/user/sshkeydir/id_rsa_git

And then clone the repository using sshkeyfile.

**Comment by crazycodr** [comment]
So i'll close this issue as it isn't relevant
