### ISSUE TITLE
test file crawler ignor second point

### ISSUE THREAD

**Issue by kamyabkh** [prancer-io/cloud-validation-framework#209]
when i use version in test file, like: 
``` version=1.2.3 ```
The crawler  does not consider one of the points and the output is displayed as follows :
```version=1.23```

![image](https://user-images.githubusercontent.com/76039122/110386603-bf10a480-8075-11eb-919e-861b0637ef20.png)

![image](https://user-images.githubusercontent.com/76039122/110386639-cb94fd00-8075-11eb-9dc5-5aa1a85e9569.png)

**Comment by ajeybk** [comment]
Fixed and released in V1.1.3
