### ISSUE TITLE
on screen output of running prancer basic

### ISSUE THREAD

**Issue by farchide** [prancer-io/cloud-validation-framework#218]
When running prancer basic from the command line, there are certain items shown on the screen.
We should make sure these items are descriptive enough for users running the platform.

Here are the suggestions for different results.  This information should be shown all the time regardless of the log level:

When the test is passed:
```
TEST_ID: 
SNAPSHOT_ID: 
PATHS: 
TITLE: 
RULE:
RESULT: PASSED
```

When the result is failed:
```
TEST_ID: 
SNAPSHOT_ID: 
PATHS: 
TITLE: 
DESCRIPTION:
RULE:
ERROR:
REMEDIATION:
RESULT: FAILED
```

When the test is skipped (empty):
```
TEST_ID: 
SNAPSHOT_ID: 
PATHS: 
RESULT: SKIPPED
```

**Comment by vatsalgit5118** [comment]
Released in 1.1.2.
