### ISSUE TITLE
Result SKIPPED should be available just in the DEBUG mode

### ISSUE THREAD

**Issue by farchide** [prancer-io/cloud-validation-framework#225]
When running the IaC Scan with prancer platform, every single template will be scanned with all available tests. If the type of the resource is different from the test, then it shows `RESULT: SKIPPED` on the screen.
this information should be available in the DEBUG mode. in other log types, we should hide this info to be shown on screen.
only the test cases with the `Passed` and `Failed` results should be visible on the screen.

**Comment by vatsalgit5118** [comment]
Released in 1.1.3.
