### ISSUE TITLE
problem in terraform processor for multiple blocks with the same name

### ISSUE THREAD

**Issue by farchide** [prancer-io/cloud-validation-framework#290]
Prancer terraform processor cannot fully `attributes as block`:
handle https://www.terraform.io/docs/language/attr-as-blocks.html

Because prancer engine converts terraform code to JSON, when we have multiple blocks of code with the same name, prancer overwrites the value of the nodes and keeps the last one.
an example of the terraform code with attributes as code:

https://github.com/prancer-io/prancer-terramerra/blob/8e1986c6f228dc84b32d7d8dd522690ed18d20e6/aws/sg/extrasg.tf#L110
https://github.com/prancer-io/prancer-terramerra/blob/8e1986c6f228dc84b32d7d8dd522690ed18d20e6/aws/sg/extrasg.tf#L126

**suggested solutions:**
When generating the JSON nodes, if the node contains a value, convert the node to a list and add a new item to the list

**Comment by vatsalgit5118** [comment]
Fixed issue in release prancer-basic 1.2.0.
