### ISSUE TITLE
is there a way to run compliance on single test case out of a testSet instead of running them all?

### ISSUE THREAD

**Issue by rezoan** [prancer-io/cloud-validation-framework#296]
I want to run compliance test for only testcase with `"masterTestId": "TEST_NETWORK_SECURITY_GROUP_1"` from [https://github.com/prancer-io/prancer-compliance-test/blob/master/azure/terraform/master-compliance-test.json](https://github.com/prancer-io/prancer-compliance-test/blob/master/azure/terraform/master-compliance-test.json)
and don't want to test others on purpose.
Thing is when i ran `prancer compliance scenario-terraform-azure` it basically running the compliance on all the test cases available in a **testSet** under `master-compliance-test.json` which is time consuming during development for each fix and test an individual test case.
**Note:** i saw a `--test` parameter in prancer but not sure is it the right parameter to test an individual testcase out of a **testSet**
i tried running ` "prancer --test TEST_NETWORK_SECURITY_GROUP_1 --compliance scenario-terraform-azure" ` but seems its not working.

**Any idea if this feature available. if available any doc reference would be helpful.**

**Comment by farchide** [comment]
@ajeybk 
We should be able to run prancer for the following scenarios:
1. a single snapshot Id for all the compliance tests
2. a single test for all snaphot Ids
3. a single snapshot id and a single test id

**Comment by farchide** [comment]
@ajeybk @rezoan scheduled for implementation

**Comment by ajeybk** [comment]
These are the different scenarios and options being added to this change:

prancer collection_name -mastersnapshotid 1,2,3
prancer collection_name -mastertestid a,b,c
prancer collection_name -mastersnapshotid 1 -mastertestid a
