### ISSUE TITLE
Content of the snapshot to be stored as an attribute

### ISSUE THREAD

**Issue by ajeybk** [prancer-io/cloud-validation-framework#310]
As support for different content type is added, the source data content type needs to be known for further processing. 
All data is processed in json, so the source content type is converted to json and from json to original format. 
The content type helps to call the appropriated converters for further processing.

In AWS IaC is processing **.template** and **.txt** file only to json.
It should also be able to process for yaml.

**Comment by jaiminswan** [comment]
Merged into master
