### ISSUE TITLE
json is not generating from azurerm_subnet_network_security_group_association terraform resource.

### ISSUE THREAD

**Issue by rezoan** [prancer-io/cloud-validation-framework#322]
Please look into terraform resource `azurerm_subnet_network_security_group_association `at https://github.com/prancer-io/prancer-terramerra/blob/master/azure/vnetsubnets/main.tf

The related json block for `azurerm_subnet_network_security_group_association `is missing from `PRANCER-HELLO-WORLD -> validation -> scenario-terraform-azure -> snapshots -> TRF_TEMPLATE_SNAPSHOT34`

**Comment by rezoan** [comment]
@ajeybk seem the snapshot is generating now. can close this issue.

**Comment by jaiminswan** [comment]
closing as per comment

**Comment by rezoan** [comment]
verified again and seems snapshot is getting generated correctly.
