### ISSUE TITLE
Multiple test cases are getting skipped though template exist in prancer web portal during compliance.

### ISSUE THREAD

**Issue by rezoan** [prancer-io/cloud-validation-framework#385]
- **PR-AZR-TRF-AGW-004** test case is getting skipped though template exist at https://github.com/prancer-io/prancer-terramerra/tree/development/azure/applicationgateways
- **PR-AZR-TRF-AGW-005** test case is getting skipped though template exist at https://github.com/prancer-io/prancer-terramerra/tree/development/azure/applicationgateways
- **PR-AZR-TRF-AGW-006** test case is getting skipped though template exist at https://github.com/prancer-io/prancer-terramerra/tree/development/azure/applicationgateways
- **PR-AZR-TRF-VM-001** test case is getting skipped though template exist at https://github.com/prancer-io/prancer-terramerra/tree/development/azure/vm
- **PR-AZR-TRF-VM-003** test case is getting skipped  though template exist at https://github.com/prancer-io/prancer-terramerra/tree/development/azure/vm

**Comment by ajeybk** [comment]
In the https://github.com/prancer-io/prancer-compliance-test/blob/development/azure/terraform/master-compliance-test.json the  "masterSnapshotId": ["ARM_TEMPLATE_SNAPSHOT"] should be "masterSnapshotId": ["TRF_TEMPLATE_SNAPSHOT"]

In https://github.com/prancer-io/prancer-compliance-test/blob/test_missing_ids/azure/terraform/master-compliance-test.json I have corrected and tested and I can see the test is not getting skipped. 

Can u please update and file a PR to development and test again ?

**Comment by rezoan** [comment]
updated the master snapshot id for

PR_AZR_TRF_AGW_004
PR_AZR_TRF_AGW_005
PR_AZR_TRF_AGW_006

any idea about other 2 item?
PR-AZR-TRF-VM-001
PR-AZR-TRF-VM-003

**Comment by jaiminswan** [comment]
Merged in master but it should be in compliance test repo

**Comment by rezoan** [comment]
**PR-AZR-TRF-VM-003** is still getting skipped.

**Comment by rezoan** [comment]
PR-AZR-TRF-VM-003 is now not getting skipped. issue been fixed. closing the issue.
