### ISSUE TITLE
Add compiletime_identity to Azure terraform resource snapshot.

### ISSUE THREAD

**Issue by rezoan** [prancer-io/cloud-validation-framework#391]
01. If resource is defined with `module`, we need to add a property `compiletime_identity `in the resource snapshot with value `"module.{modulename}"`
02. If resource is defined with `data`, we need to add a property `compiletime_identity `in the resource snapshot with value `"data.{resource_type}.{alies}"`
03. If resource is defined with generic `resource`, we need to add a property `compiletime_identity `in the resource snapshot with value `"{resource_type}.{alies}"`

**Comment by farchide** [comment]
@vatsalgit5118 please prioritize this issue

**Comment by rezoan** [comment]
@vatsalgit5118 not working for module.
For example: Look into `applicationgateways` in azure terramerra repo at https://github.com/prancer-io/prancer-terramerra/blob/master/azure/applicationgateways/main.tf. 
it has 2 subnet module `subnet-frontend` and `subnet-backend` but in the snapshot both has `"compiletime_identity": "azurerm_subnet.sub"` which is wrong. also the name in the snapshot (highlighted outside of property) is not correct. inside property one is correct.
![image](https://user-images.githubusercontent.com/1701375/144353589-b56a60a5-40fd-4e92-b2b9-9be7d18a8903.png)
![image](https://user-images.githubusercontent.com/1701375/144353645-3f48f120-a7b9-42be-bc2d-99d8e9741104.png)

one should have `"compiletime_identity": "module.subnet-frontend"` and another should have `"compiletime_identity": "module.subnet-backend"`

Also i did saw for **data** resource, `compliletime_identity `is being generated outside of property and for resource it being generated inside `property`. Please make it consistent. **outside of property is preferred.**
![image](https://user-images.githubusercontent.com/1701375/144353751-ea2359f6-319b-438d-b977-ef63ddcd32f0.png)

![image](https://user-images.githubusercontent.com/1701375/144353700-75a2c3ca-7e7b-4748-b7b5-3696e5d39a96.png)
