### ISSUE TITLE
Azure cloud snapshots to be wrapped in resources array

### ISSUE THREAD

**Issue by rezoan** [prancer-io/cloud-validation-framework#399]
Wrap the resource inside a resources[] array in snapshot, then there will be no need to write redundant rego rules as these are already present in azure ARM IAC and we end up maintaining only one set of rego files.

**Comment by farchide** [comment]
@ajeybk  please start working on this as soon as you find the time.
Before the release, we should update all the Rego files related to Azure cloud though.
