### ISSUE TITLE
Modification needed in prancer basic for list api's response.

### ISSUE THREAD

**Issue by ishan-pansuriya** [prancer-io/cloud-validation-framework#593]
- There are two limitations have been encountered in prancer-basic code:
	1) Current code of prancer-basic only fetching "items"(i.e. value of the keyword 'items') from the receiving list api's response. However, some of the api doesn't have the keyword "items" in the response, which needs to be taken care of.
	2) Apart from this, an api ServiceAccounKey is an another exception because in order to crawl the expected resources we need to call 3 different kind of api's, which is another modification that we need to make.

**Comment by jaiminswan** [comment]
Merged into master
