### ISSUE TITLE
Crawler is not crawling Azure roleAssignments

### ISSUE THREAD

**Issue by rezoan** [prancer-io/cloud-validation-framework#681]
- First crawl role assignment list from: https://learn.microsoft.com/en-us/rest/api/authorization/role-assignments/list-for-scope?tabs=HTTP#code-try-0
- Then for each **roleDefinitionId** from each **Microsoft.Authorization/roleAssignments** get role definition details by id from: https://learn.microsoft.com/en-us/rest/api/authorization/role-definitions/get-by-id?tabs=HTTP#code-try-0
- create a new custom object property named **roleDefinition** under each **Microsoft.Authorization/roleAssignments** property block and put the output object from previous step.

**Comment by vatsalgit5118** [comment]
Added support to crawl the Azure roleAssignments. Feature released in `prancer-basic==3.0.9` version
