### ISSUE TITLE
GCP is not crawling "masterSnapshotId": "GOOGLE_CLUSTER"

### ISSUE THREAD

**Issue by rezoan** [prancer-io/cloud-validation-framework#709]
**During running compliances no snapshots are being generated for GOOGLE_CLUSTER**
- MasterSnapshotid is at: https://github.com/prancer-io/prancer-compliance-test/blob/dev-rezoan-gcp/google/cloud/master-snapshot.json#L8
- googleParams.json is at https://github.com/prancer-io/prancer-hello-world/blob/rezoan-patch-2/googleParams.json
- K8 compliances is at https://github.com/prancer-io/prancer-compliance-test/blob/dev-rezoan-gcp/google/cloud/container.rego

**Crawler console output:**
```
2023-09-17 12:54:51,878 - 	Snapshot:
2023-09-17 12:54:51,878 - 	GOOGLE_CLUSTER:[] 
```

**Comment by vatsalgit5118** [comment]
@rezoan, I checked the API response, it contains the `selfLink`, so not required to set the `get_method` in mastersnapshot.
Remove the `get_method` method from the master snapshot and the `container/projects.locations.clusters.get` parameter from the googleParams.json file.

**Comment by rezoan** [comment]
@vatsalgit5118 @farchide crawler is now crawling GOOGLE_CLUSTER. issue can be closed.
