### ISSUE TITLE
GCP is not crawling "masterSnapshotId": "GOOGLE_INSTANCE"

### ISSUE THREAD

**Issue by rezoan** [prancer-io/cloud-validation-framework#710]
**During running compliances no snapshots are being generated for GOOGLE_INSTANCE**

- MasterSnapshotid is at: https://github.com/prancer-io/prancer-compliance-test/blob/dev-rezoan-gcp/google/cloud/master-snapshot.json#L74
googleParams.json is at https://github.com/prancer-io/prancer-hello-world/blob/rezoan-patch-2/googleParams.json
Compute instance compliances is at https://github.com/prancer-io/prancer-compliance-test/blob/dev-rezoan-gcp/google/cloud/compute.rego

**Crawler console output:**
```
2023-09-17 12:54:51,878 - 	Snapshot:
2023-09-17 12:54:51,879 - 	GOOGLE_INSTANCE:[]
```

**Comment by vatsalgit5118** [comment]
@rezoan, I checked the API response, it contains the `selfLink`, so not required to set the `get_method` in mastersnapshot.
Remove the `get_method` method from the master snapshot and the `compute/instances.get` parameter from the googleParams.json file.

**Comment by rezoan** [comment]
@vatsalgit5118 @farchide crawler is crawling GOOGLE_INSTANCE. this issue can be closed.
