### ISSUE TITLE
GCP is not crawling "masterSnapshotId": "GOOGLE_PROJECTS_IDENTITY_PLATFORM_ACCOUNTS"

### ISSUE THREAD

**Issue by rezoan** [prancer-io/cloud-validation-framework#711]
During running compliances no snapshots are being generated for GOOGLE_PROJECTS_IDENTITY_PLATFORM_ACCOUNTS

MasterSnapshotid is at: https://github.com/prancer-io/prancer-compliance-test/blob/dev-rezoan-gcp/google/cloud/master-snapshot.json#L362
googleParams.json is at https://github.com/prancer-io/prancer-hello-world/blob/rezoan-patch-2/googleParams.json
IAM compliances is at https://github.com/prancer-io/prancer-compliance-test/blob/dev-rezoan-gcp/google/cloud/iam.rego#L670

**Crawler console output:**
```
2023-09-17 12:54:51,878 - 	Snapshot:
2023-09-17 12:54:51,904 - 	GOOGLE_PROJECTS_IDENTITY_PLATFORM_ACCOUNTS:false
```

**Comment by vatsalgit5118** [comment]
@rezoan, please include the `get_method` in master snapshot file with `identitytoolkit/projects.accounts.batchGet` value.
Also, add the following parameters in the googleParams.json inside `GoogleGetApis`.
```
"identitytoolkit/projects.accounts.batchGet": {
    "url" : "https://identitytoolkit.googleapis.com/v1/projects/{project}/accounts:batchGet"
}
```

**Comment by rezoan** [comment]
@vatsalgit5118 @farchide snapshots are generating correctly. can close this issue.
